### ISSUE TITLE
Reintroduce ResourceCollection into Ui namespace

### ISSUE THREAD

**Issue by MrHash** [honeybee/honeybee#32]

**Comment by shrink0r** [comment]
👍

**Comment by graste** [comment]
`ProjectionCollection` items will be added to that `ResourceCollection` in the actions (`CollectionAction` etc. in the CMF)

**Comment by Pictor13** [comment]
ref c7efcf1 bf5e49e

**Comment by graste** [comment]
Almost done.

ResourceCollection should not extend EntityList as it's more of an abstract concept at the moment and it shouldn't actually matter whether the resources are Honeybee Entities. The ResourceCollection renderer should not care for the actual base type of the resources – thus the missing containsMultipleTypes method could be solved by e.g. extending ArrayList and introducing the method there so that the renderer can stay like it is now.

**Comment by MrHash** [comment]
ref e1fab5f4cd15baee5eec98573ce53a3ff1dc928f
